title: "MLOpsハンズオン環境構築(MLflow Tracking/Prefect)"
summary: "MLOpsの中でも実験管理(MLflow Tracking)とワークフロー(Prefect)のハンズオンを行うための環境を構築する。"
topics: ["MLOps", "MLflow", "prefect", "minio"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 01_intro
  - 02_conf
  - 11_minio
  - 12_mlflow_server
  - 21_jupyterlab
  - 22_prefect
  - 91_docker
