title: "個人開発におけるGitワークフロー入門"
summary: "Gitにおけるワークフローとして、Git FlowやGitHub Flowなどが有名だが、ここでは個人開発に適したワークフローであるGit フィーチャーブランチワークフローについて取り扱う。"
topics: ["git", "github", "gitlab"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 001_intro
  - 100_handson_00
  - 101_handson_01
  - 102_handson_02

